#!/bin/bash

#SBATCH --chdir=/data/project/jbrose3-lab/Gina/FastQ
#SBATCH --nodes=1
#SBATCH --job-name=FastQC
#SBATCH --ntasks=1
#SBATCH --partition=express
#SBATCH --mem-per-cpu=12G
#SBATCH --cpus-per-task=1
#SBATCH --out=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --time=02:00:00
#SBATCH --mail-user=gcjosey@uab.edu
#SBATCH --mail-type=ALL
	

module load Anaconda3/5.3.1
conda activate cutadapt

conda create --name xxxxxxx


module load Anaconda3/2023.07-2
gencode.v47.annotation.gtf.gz
gencode.v47.transcripts.fa.gz
Anaconda3/2023.07-2
